### ISSUE TITLE
Add support for non-paid ERDs

### ISSUE THREAD

**Issue by tcaruth** [oracle/quicksql#30]
I'd love to see a way to quickly build ERDs without purchasing Joint+. It'd be nice to use that feature without needing to pay $3k USD.

Have other (free) or open-source options like MermaidJS or bpmn.io been explored?

**Comment by krisrice** [comment]
yes we explored many options for full ER modeling inside sqldev-web which this quicksql version is a paired down subset

**Comment by mig8447** [comment]
We welcome push requests that enhance the functionality of the product, but for the time being this is not a planned feature/enhancement
