### ISSUE TITLE
Audit columns table directives only work with no space, contrary to the documentation

### ISSUE THREAD

**Issue by tcaruth** [oracle/quicksql#31]
Documentation states:
| Directive | Description |
| -- | -- |
| /auditcols, /audit cols, /audit columns | Automatically adds an UPDATED, UPDATED_BY, INSERTED, and INSERTED_BY columns and the trigger logic to set column values. |

I'm unable to get `/audit cols` or `/audit columns` to work correctly in version 1.15, only `/auditcols` is working.

My example quick sql:
```
departments /audit cols
    name 
    employees /auditcols
        name /nn vc50
    another table /auditcols
        name
```
Tested at https://krisrice.io/quick-sql-standalone.html

**Comment by vadim-tropashko** [comment]
1.2.1
