### ISSUE TITLE
Output DDL has `undefined` for QuickSQL version

### ISSUE THREAD

**Issue by neilfernandez** [oracle/quicksql#35]
QuickSQL input:

```
dept
    name
```

The commented section in the output DDL has the following:

```
-- Generated by Quick SQL undefined 12/6/2023, 12:22:36 AM

/*
dept
    name

 Non-default options:
# settings = {}

*/
```
After `-- Generated by Quick SQL` it should have the QuickSQL version instead of `undefined`

**Comment by vadim-tropashko** [comment]
Tested at https://krisrice.io/quick-sql-standalone.html:

`-- create tables

create table dept (
    id    number generated by default on null as identity
          constraint dept_id_pk primary key
);



-- Generated by Quick SQL 1.2.1 2/13/2024, 3:21:37 PM
`

**Comment by vadim-tropashko** [comment]
in 1.2.1
