### ISSUE TITLE
Add support for check constraints other than "value in list"

### ISSUE THREAD

**Issue by dmcghan** [oracle/quicksql#37]
QSQL currently supports check constraints at the column level, but only for "value in list" types of constraints. There are lots of other types of constraints we might want to model in QSQL. For example, you might want to ensure values in a number column are higher or lower than a fixed value. Or you might want to ensure text going into a text column is a certain case.

Such constraints would require QSQL to allow the developer to provide an expression and (potentially) a name for the constraint.

**Comment by vadim-tropashko** [comment]
implemented in 1.2.1, see https://github.com/oracle/quicksql/blob/main/test/constraints.qsql
