### ISSUE TITLE
When there are more tables on the diagram, the tables overlap each other.

### ISSUE THREAD

**Issue by alahe** [oracle/quicksql#41]
I In this example, we are using 15 tables. Also, it's not possible to shrink the diagram to see the whole picture, nor can it be saved as an image.

<img width="987" alt="image" src="https://github.com/oracle/quicksql/assets/18213328/a9d5f047-d636-4287-b3c3-5211a065c4a4">

**Comment by zahariev-oracle** [comment]
You can try to ZoomIn and ZoomOut the diagram holding Shift+Mouse wheel
For exporting the diagram try alt+S

**Comment by alahe** [comment]
Thanks, Zahariev, for your feedback. The keyboard shortcuts you recommended are working well, and I appreciate your suggestion. However, the issue has come up again. Once more, one table was drawn over the other.
![image](https://github.com/oracle/quicksql/assets/18213328/00487afe-3d2a-43f9-934b-cbeb861c8e90)

I attached Quick SQL file 
[competition.txt](https://github.com/oracle/quicksql/files/14324442/competition.txt)

**Comment by zahariev-oracle** [comment]
Hi Allan,
I will change the autolayout algorithm in the next version and also will allow manual movements of the tables.
