### ISSUE TITLE
Use key words in the column name to default the data type

### ISSUE THREAD

**Issue by simonhunt8475** [oracle/quicksql#46]
Currently in quickSQL if the column name includes _number then it defaults the column to NUMBER and _date to DATE.  Prior to 23.2 _name would defalt to VC255, but that has now gone.  I would suggest this is reinstated, but shortened to the length at which the builder creates a Text Field rather than a Text Area.  I would do the same for _title.

Implicitly, this should set test_name = vc90, test_description = vc4000, test_number = numeric and test_date = date

<img width="1569" alt="Screenshot 2024-01-27 at 22 17 45" src="https://github.com/oracle/quicksql/assets/125390039/640d39a4-a918-44f6-b906-9b8b8b4cae97">

**Comment by vadim-tropashko** [comment]
Fixed in 1.2.1
