### ISSUE TITLE
email address parsing error for column defaults

### ISSUE THREAD

**Issue by damithkothalawala** [oracle/quicksql#48]
how to replicate the issue

support
       support_email vc100 /default support@oracle.com
       
expected column

support_email     varchar2(100 char) default on null 'support@oracle.com',

what I got is out of range 102399 for varchar length. Seems something to do with @ handling. 

support_email     varchar2(102399 char) default on null 'support@oracle.com',

**Comment by vadim-tropashko** [comment]
https://krisrice.io/quick-sql-standalone.html which runs 1.1.4 outputs:

create table support (
    id               number generated by default on null as identity
                     constraint support_id_pk primary key,
    support_email    varchar2(100 char) default on null 'support'
);

which is still a bug, albeit a different one

**Comment by vadim-tropashko** [comment]
1.2.1

**Comment by damithkothalawala** [comment]
Thank you 🙏🏻
