### ISSUE TITLE
Boolean Datatype 23c (Was: Order of 'default' with boolean produces invalid SQL)

### ISSUE THREAD

**Issue by dmcghan** [oracle/quicksql#51]
This Quick SQL:
```yaml
foo
  bar /boolean /default y
```

Creates this SQL:
```sql
create table foo (
    id     number generated by default on null as identity
           constraint foo_id_pk primary key,
    bar    varchar2(1 char) constraint foo_bar
           check (bar in ('Y','N')) 
);
```

Oracle throws ORA-00907: missing right parenthesis.

If `default on null 'y'` is moved before the constraint then the statement runs fine.

**Comment by vadim-tropashko** [comment]
1.2.1:
`create table foo (
    id     number generated by default on null as identity
           constraint foo_id_pk primary key,
    bar    varchar2(1 char) default on null 'y'
           constraint foo_bar check (bar in ('Y','N'))
);
`

**Comment by vadim-tropashko** [comment]
Boolean datatype it is

**Comment by vadim-tropashko** [comment]
```
#boolean: yn           -- default
#boolean: native     -- 23c
```

**Comment by neilfernandez** [comment]
Brilliant. So if my `db` setting < 23, even if I put boolean, can we convert it to varchar2 for that scenario?

![image](https://github.com/oracle/quicksql/assets/9313239/46c378e4-932d-4b07-a24b-76c0b7d7543a)

**Comment by vadim-tropashko** [comment]
`db` parameter is not used. If there is another db-dependent feature, then we might introduce it to influence the dependent options default values in bulk

**Comment by vadim-tropashko** [comment]
The `db` option is right there [in the doc](https://github.com/oracle/quicksql/blob/main/doc/user/quick-sql-grammar.md); will nuke it until further notice.
